# Generated by Django 5.1 on 2024-08-28 17:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('details', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(default=datetime.datetime(2024, 8, 28, 20, 23, 11, 899625))),
                ('status', models.CharField(choices=[('cancelled', 'Cancelled'), ('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=30)),
            ],
        ),
    ]
